/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class test */

#ifndef _Included_test
#define _Included_test
#ifdef __cplusplus
extern "C" {
#endif
#undef test_FOCUS_TRAVERSABLE_UNKNOWN
#define test_FOCUS_TRAVERSABLE_UNKNOWN 0L
#undef test_FOCUS_TRAVERSABLE_DEFAULT
#define test_FOCUS_TRAVERSABLE_DEFAULT 1L
#undef test_FOCUS_TRAVERSABLE_SET
#define test_FOCUS_TRAVERSABLE_SET 2L
#undef test_TOP_ALIGNMENT
#define test_TOP_ALIGNMENT 0.0f
#undef test_CENTER_ALIGNMENT
#define test_CENTER_ALIGNMENT 0.5f
#undef test_BOTTOM_ALIGNMENT
#define test_BOTTOM_ALIGNMENT 1.0f
#undef test_LEFT_ALIGNMENT
#define test_LEFT_ALIGNMENT 0.0f
#undef test_RIGHT_ALIGNMENT
#define test_RIGHT_ALIGNMENT 1.0f
#undef test_serialVersionUID
#define test_serialVersionUID -7644114512714619750i64
#undef test_serialVersionUID
#define test_serialVersionUID 4613797578919906343i64
#undef test_INCLUDE_SELF
#define test_INCLUDE_SELF 1L
#undef test_SEARCH_HEAVYWEIGHTS
#define test_SEARCH_HEAVYWEIGHTS 1L
#undef test_serialVersionUID
#define test_serialVersionUID -2728009084054400034i64
#undef test_serialVersionUID
#define test_serialVersionUID -5836846270535785031i64
/*
 * Class:     test
 * Method:    myout
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_test_myout
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
